//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPosuda.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KorobeynikovaPosudaEntities : DbContext
    {
        public KorobeynikovaPosudaEntities()
            : base("name=KorobeynikovaPosudaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clietn> Clietn { get; set; }
        public virtual DbSet<Postavchik> Postavchik { get; set; }
        public virtual DbSet<Proizvod> Proizvod { get; set; }
        public virtual DbSet<Punkt> Punkt { get; set; }
        public virtual DbSet<RoleSotrudnik> RoleSotrudnik { get; set; }
        public virtual DbSet<Sotrydnik> Sotrydnik { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<TovarCategory> TovarCategory { get; set; }
        public virtual DbSet<TovarName> TovarName { get; set; }
        public virtual DbSet<TypeClient> TypeClient { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
    }
}
