//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPosuda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydnik
    {
        public int id { get; set; }
        public Nullable<int> id_role_sotr { get; set; }
        public string fio_sotr { get; set; }
        public string login_sotr { get; set; }
        public string pass_sotr { get; set; }
    
        public virtual RoleSotrudnik RoleSotrudnik { get; set; }
    }
}
