//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPosuda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public string articyl_tovar { get; set; }
        public Nullable<int> id_name_tovar { get; set; }
        public string ediz_tovar { get; set; }
        public Nullable<double> cost_tovar { get; set; }
        public Nullable<double> max_sale_tovar { get; set; }
        public Nullable<int> id_proizvod_tovar { get; set; }
        public Nullable<int> id_poctavchik_tovar { get; set; }
        public Nullable<int> id_kategiry_tovar { get; set; }
        public Nullable<double> curent_sale_tovar { get; set; }
        public Nullable<double> kolvo_tovar { get; set; }
        public string deck_tovar { get; set; }
        public string image_tovar { get; set; }
    
        public virtual Postavchik Postavchik { get; set; }
        public virtual Proizvod Proizvod { get; set; }
        public virtual TovarCategory TovarCategory { get; set; }
        public virtual TovarName TovarName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
