//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoPosuda.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int id { get; set; }
        public string id_artic_zakaz { get; set; }
        public Nullable<double> kolvo_tovar_in_zakaz { get; set; }
        public Nullable<System.DateTime> data_zakaz { get; set; }
        public Nullable<System.DateTime> data_dostav_zakaz { get; set; }
        public Nullable<int> id_punkt_zakaz { get; set; }
        public Nullable<int> id_name_client { get; set; }
        public Nullable<double> kod_zakaz { get; set; }
        public Nullable<int> id_state_zakaz { get; set; }
    
        public virtual Clietn Clietn { get; set; }
        public virtual Punkt Punkt { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
